### ISSUE TITLE
Is there nothing?

### ISSUE THREAD

**Issue by LuckyJLin** [nlpbank/SRP2Vec#1]
Hi, I come here from your paper published in ACL_2018. 
When can I see codes here? 
So appreciate to you!

**Comment by nlpbank** [comment]
Sorry for the late response. Due to the copyright issue with the sponsored company, the publication of code and data has been ㅇdelayed inevitably. The experimental results and pretrained word vector representations are uploaded in "https://zenodo.org/record/4412086#.X_HDVmgzaUk". The source code will be available very very soon (within a week).
